# -*- coding: utf-8 -*-
"""AI_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wng6SNcenOc7ZLa36SvwcLu1ptAZ533L
"""

pip install pandas numpy scikit-learn gradio joblib

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    r2_score,
    mean_absolute_percentage_error
)


# -----------------------------
# 1. Load dataset
# -----------------------------
df = pd.read_csv("restaurant_data.csv")

target = "Revenue"

categorical_features = [
    "Location",
    "Cuisine",
    "Parking Availability"
]

numeric_features = [
    "Rating",
    "Seating Capacity",
    "Average Meal Price",
    "Marketing Budget",
    "Social Media Followers",
    "Chef Experience Years",
    "Number of Reviews",
    "Avg Review Length",
    "Ambience Score",
    "Service Quality Score",
    "Weekday Reservations",
    "Weekend Reservations"
]

X = df[categorical_features + numeric_features]
y = df[target]


# -----------------------------
# 2. Train-test split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


# -----------------------------
# 3. Preprocessing
# -----------------------------
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_transformer, numeric_features),
        ("categorical", categorical_transformer, categorical_features)
    ]
)


# -----------------------------
# 4. Model with warm_start
# -----------------------------
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
        n_estimators=10,
        random_state=42,
        max_depth=10,
        min_samples_leaf=3,
        warm_start=True
    ))
])


# -----------------------------
# 5. Train model step-by-step
# -----------------------------
print("Training Progress")
print("-----------------")

progress_results = []

for trees in range(10, 301, 10):
    model.set_params(regressor__n_estimators=trees)

    model.fit(X_train, y_train)

    train_predictions = model.predict(X_train)
    test_predictions = model.predict(X_test)

    train_mae = mean_absolute_error(y_train, train_predictions)
    test_mae = mean_absolute_error(y_test, test_predictions)

    train_r2 = r2_score(y_train, train_predictions)
    test_r2 = r2_score(y_test, test_predictions)

    test_mape = mean_absolute_percentage_error(y_test, test_predictions)
    approximate_accuracy = max(0, 100 * (1 - test_mape))

    progress_results.append({
        "Trees": trees,
        "Train MAE": train_mae,
        "Test MAE": test_mae,
        "Train R2": train_r2,
        "Test R2": test_r2,
        "Approx Accuracy %": approximate_accuracy
    })

    print(
        f"Trees: {trees:3d} | "
        f"Train MAE: ${train_mae:,.2f} | "
        f"Test MAE: ${test_mae:,.2f} | "
        f"Train R²: {train_r2:.3f} | "
        f"Test R²: {test_r2:.3f} | "
        f"Approx Accuracy: {approximate_accuracy:.2f}%"
    )

  # Get trained random forest from pipeline
rf_model = model.named_steps["regressor"]

# Get feature names after preprocessing
feature_names = model.named_steps["preprocessor"].get_feature_names_out()

# Create feature importance table
importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf_model.feature_importances_
})

importance_df = importance_df.sort_values(by="Importance", ascending=False)

print(importance_df.head(15))


# -----------------------------
# 6. Final evaluation
# -----------------------------
final_predictions = model.predict(X_test)

final_mae = mean_absolute_error(y_test, final_predictions)
final_r2 = r2_score(y_test, final_predictions)
final_mape = mean_absolute_percentage_error(y_test, final_predictions)
final_accuracy = max(0, 100 * (1 - final_mape))

print()
print("Final Model Evaluation")
print("----------------------")
print(f"Mean Absolute Error: ${final_mae:,.2f}")
print(f"R² Score: {final_r2:.3f}")
print(f"Approximate Accuracy: {final_accuracy:.2f}%")


# -----------------------------
# 7. Save model
# -----------------------------
joblib.dump(model, "restaurant_revenue_model.pkl")

print()
print("Model saved as restaurant_revenue_model.pkl")


# -----------------------------
# 8. Optional: save progress table
# -----------------------------
progress_df = pd.DataFrame(progress_results)
progress_df.to_csv("training_progress.csv", index=False)

print("Training progress saved as training_progress.csv")