# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18myIeHsGv-7QIH0QaAKzXM-Y9MS1SA2Y
"""

import gradio as gr
import pandas as pd
import numpy as np
import joblib


# --------------------------------------------------
# 1. Load trained model
# --------------------------------------------------
model = joblib.load("restaurant_revenue_model.pkl")


# --------------------------------------------------
# 2. Build input dataframe
# --------------------------------------------------
def build_input_dataframe(
    location,
    cuisine,
    rating,
    seating_capacity,
    average_meal_price,
    marketing_budget,
    social_media_followers,
    chef_experience_years,
    number_of_reviews,
    avg_review_length,
    ambience_score,
    service_quality_score,
    parking_available,
    weekend_reservations,
    weekday_reservations
):
    return pd.DataFrame([{
        "Location": location,
        "Cuisine": cuisine,
        "Rating": rating,
        "Seating Capacity": seating_capacity,
        "Average Meal Price": average_meal_price,
        "Marketing Budget": marketing_budget,
        "Social Media Followers": social_media_followers,
        "Chef Experience Years": chef_experience_years,
        "Number of Reviews": number_of_reviews,
        "Avg Review Length": avg_review_length,
        "Ambience Score": ambience_score,
        "Service Quality Score": service_quality_score,
        "Parking Availability": "Yes" if parking_available else "No",
        "Weekend Reservations": weekend_reservations,
        "Weekday Reservations": weekday_reservations
    }])


# --------------------------------------------------
# 3. Try to get tree-level predictions
# This lets us estimate how consistently the model
# thinks a suggestion increases revenue.
# --------------------------------------------------
def get_tree_predictions(input_data):
    try:
        preprocessor = model.named_steps["preprocessor"]
        regressor = model.named_steps["regressor"]

        transformed_input = preprocessor.transform(input_data)

        # Case 1: direct RandomForestRegressor
        if hasattr(regressor, "estimators_"):
            tree_predictions = np.array([
                tree.predict(transformed_input)[0]
                for tree in regressor.estimators_
            ])
            return tree_predictions

        # Case 2: TransformedTargetRegressor wrapping RandomForestRegressor
        if hasattr(regressor, "regressor_") and hasattr(regressor.regressor_, "estimators_"):
            raw_predictions = np.array([
                tree.predict(transformed_input)[0]
                for tree in regressor.regressor_.estimators_
            ])

            if getattr(regressor, "inverse_func", None) is not None:
                tree_predictions = regressor.inverse_func(
                    raw_predictions.reshape(-1, 1)
                ).ravel()
                return tree_predictions

            return raw_predictions

    except Exception:
        return None

    return None


# --------------------------------------------------
# 4. Suggest improvements
# Important:
# We do NOT change Seating Capacity or Average Meal Price.
# They stay fixed.
# --------------------------------------------------
def generate_suggestions(base_input, current_prediction):
    suggestions = []

    base = base_input.copy()

    scenarios = {
        "Increase marketing budget by 20%": {
            "Marketing Budget": base.loc[0, "Marketing Budget"] * 1.20
        },
        "Increase social media followers by 25%": {
            "Social Media Followers": base.loc[0, "Social Media Followers"] * 1.25
        },
        "Improve rating by 0.3 points": {
            "Rating": min(base.loc[0, "Rating"] + 0.3, 5.0)
        },
        "Increase number of reviews by 20%": {
            "Number of Reviews": base.loc[0, "Number of Reviews"] * 1.20
        },
        "Increase average review length by 10 words": {
            "Avg Review Length": base.loc[0, "Avg Review Length"] + 10
        },
        "Improve ambience score by 1 point": {
            "Ambience Score": min(base.loc[0, "Ambience Score"] + 1, 10)
        },
        "Improve service quality score by 1 point": {
            "Service Quality Score": min(base.loc[0, "Service Quality Score"] + 1, 10)
        },
        "Increase weekend reservations by 10%": {
            "Weekend Reservations": base.loc[0, "Weekend Reservations"] * 1.10
        },
        "Increase weekday reservations by 10%": {
            "Weekday Reservations": base.loc[0, "Weekday Reservations"] * 1.10
        }
    }

    # Only test adding parking if the restaurant does not already have parking
    if base.loc[0, "Parking Availability"] == "No":
        scenarios["Add or partner with nearby parking"] = {
            "Parking Availability": "Yes"
        }

    base_tree_predictions = get_tree_predictions(base)

    for suggestion_name, changes in scenarios.items():
        modified = base.copy()

        for feature, new_value in changes.items():
            modified.loc[0, feature] = new_value

        new_prediction = model.predict(modified)[0]
        estimated_gain = new_prediction - current_prediction

        # Estimate likelihood using individual trees in the random forest
        modified_tree_predictions = get_tree_predictions(modified)

        if base_tree_predictions is not None and modified_tree_predictions is not None:
            tree_gains = modified_tree_predictions - base_tree_predictions
            likelihood_increase = np.mean(tree_gains > 0) * 100
        else:
            likelihood_increase = 100 if estimated_gain > 0 else 0

        if likelihood_increase >= 70 and estimated_gain > 0:
            confidence = "High"
        elif likelihood_increase >= 50 and estimated_gain > 0:
            confidence = "Medium"
        elif estimated_gain > 0:
            confidence = "Low"
        else:
            confidence = "Not Recommended"

        suggestions.append({
            "Suggestion": suggestion_name,
            "Estimated New Revenue": new_prediction,
            "Estimated Revenue Increase": estimated_gain,
            "Model Likelihood of Increase": likelihood_increase,
            "Confidence": confidence
        })

    suggestions_df = pd.DataFrame(suggestions)

    suggestions_df = suggestions_df.sort_values(
        by="Estimated Revenue Increase",
        ascending=False
    )

    suggestions_df["Estimated New Revenue"] = suggestions_df["Estimated New Revenue"].apply(
        lambda x: f"${x:,.2f}"
    )

    suggestions_df["Estimated Revenue Increase"] = suggestions_df["Estimated Revenue Increase"].apply(
        lambda x: f"${x:,.2f}"
    )

    suggestions_df["Model Likelihood of Increase"] = suggestions_df[
        "Model Likelihood of Increase"
    ].apply(lambda x: f"{x:.1f}%")

    return suggestions_df


# --------------------------------------------------
# 5. Main prediction function
# --------------------------------------------------
def predict_and_recommend(
    location,
    cuisine,
    rating,
    seating_capacity,
    average_meal_price,
    marketing_budget,
    social_media_followers,
    chef_experience_years,
    number_of_reviews,
    avg_review_length,
    ambience_score,
    service_quality_score,
    parking_available,
    weekend_reservations,
    weekday_reservations
):
    input_data = build_input_dataframe(
        location,
        cuisine,
        rating,
        seating_capacity,
        average_meal_price,
        marketing_budget,
        social_media_followers,
        chef_experience_years,
        number_of_reviews,
        avg_review_length,
        ambience_score,
        service_quality_score,
        parking_available,
        weekend_reservations,
        weekday_reservations
    )

    predicted_revenue = model.predict(input_data)[0]

    suggestions_df = generate_suggestions(input_data, predicted_revenue)

    explanation = """
### How suggestions are generated

The revenue prediction uses all features, including seating capacity and average meal price.

However, the improvement suggestions intentionally keep seating capacity and average meal price fixed.
The app only tests more actionable changes such as marketing, social media, rating, reviews, ambience, service quality, parking, and reservations.

The likelihood score is based on how many trees in the random forest predict that the change would increase revenue.
It is a model-based estimate, not a guaranteed business outcome.
"""

    return f"${predicted_revenue:,.2f}", suggestions_df, explanation


# --------------------------------------------------
# 6. Gradio frontend
# --------------------------------------------------
with gr.Blocks(title="Restaurant Revenue Predictor") as demo:
    gr.Markdown("# Restaurant Monthly Revenue Predictor")
    gr.Markdown(
        "Enter restaurant details below. The app predicts monthly revenue and suggests possible improvements."
    )

    with gr.Row():
        with gr.Column():
            gr.Markdown("## Restaurant Information")

            location = gr.Dropdown(
                choices=["Downtown", "Suburban", "Rural"],
                value="Downtown",
                label="Location"
            )

            cuisine = gr.Dropdown(
                choices=[
                    "American",
                    "French",
                    "Italian",
                    "Japanese",
                    "Mexican"
                ],
                value="Italian",
                label="Cuisine"
            )

            rating = gr.Slider(
                minimum=1.0,
                maximum=5.0,
                value=4.2,
                step=0.1,
                label="Rating"
            )

            seating_capacity = gr.Number(
                value=80,
                label="Seating Capacity"
            )

            average_meal_price = gr.Number(
                value=30,
                label="Average Meal Price ($)"
            )

            parking_available = gr.Checkbox(
                value=True,
                label="Parking Available?"
            )

        with gr.Column():
            gr.Markdown("## Marketing and Customer Data")

            marketing_budget = gr.Number(
                value=5000,
                label="Marketing Budget ($)"
            )

            social_media_followers = gr.Number(
                value=10000,
                label="Social Media Followers"
            )

            chef_experience_years = gr.Number(
                value=8,
                label="Chef Experience Years"
            )

            number_of_reviews = gr.Number(
                value=500,
                label="Number of Reviews"
            )

            avg_review_length = gr.Number(
                value=40,
                label="Average Review Length"
            )

        with gr.Column():
            gr.Markdown("## Quality and Reservation Data")

            ambience_score = gr.Slider(
                minimum=1,
                maximum=10,
                value=8,
                step=0.1,
                label="Ambience Score"
            )

            service_quality_score = gr.Slider(
                minimum=1,
                maximum=10,
                value=8,
                step=0.1,
                label="Service Quality Score"
            )

            weekend_reservations = gr.Number(
                value=400,
                label="Weekend Reservations per Month"
            )

            weekday_reservations = gr.Number(
                value=250,
                label="Weekday Reservations per Month"
            )

    predict_button = gr.Button("Predict Revenue and Suggest Improvements")

    predicted_output = gr.Textbox(
        label="Predicted Monthly Revenue"
    )

    suggestions_output = gr.Dataframe(
        label="Suggested Improvements",
        wrap=True
    )

    explanation_output = gr.Markdown()

    predict_button.click(
        fn=predict_and_recommend,
        inputs=[
            location,
            cuisine,
            rating,
            seating_capacity,
            average_meal_price,
            marketing_budget,
            social_media_followers,
            chef_experience_years,
            number_of_reviews,
            avg_review_length,
            ambience_score,
            service_quality_score,
            parking_available,
            weekend_reservations,
            weekday_reservations
        ],
        outputs=[
            predicted_output,
            suggestions_output,
            explanation_output
        ]
    )


if __name__ == "__main__":
    demo.launch()